Don't exit if a mod isn't found, keep checking the rest of the list
ominitay/shellsaber pull request #12
Opened 2021-09-04 21:46 UTC by mtfurlan

When the game updates and I need to update all the mods, it's annoying to have
to take my list of mods and remove successes or fails one by one till I have a
list of the mods that have updated and the ones that haven't.

It's much nicer if shaber just tells me that some failed, and the rest updated
or whatever.

I tested this against mod update and mod download, it seems to be fine for both
of those when passed a mixed list of updated and non-updated mods.
If there is any other testing you want done let me know.

Also it's real nice to work on bash scripts from someone else that already pass
shellcheck, thank you.

2021-09-04 23:22 UTC, ominitay commented
Thank you for this PR! I'll review this tomorrow, and make any changes needed.

2021-09-07 13:03 UTC, ominitay requested changes
A few style changes needed, and a more standard way of handling these errors is needed. I'll have go at implementing these :)

2021-09-07 13:03 UTC, ominitay commented on shaber
> +          log_error "Couldn't find dependency $dependency for $1"; exit 1
Perhaps instead of logging an error here, we could print the dependency name and return 1, so the parent function can handle it.

2021-09-07 13:03 UTC, ominitay commented on shaber
> +  if [ -z "$mod_json" ]; then
Same here

2021-09-07 13:03 UTC, ominitay commented on shaber
> +    if [ -z "$mod_json" ]; then
Same here

2021-09-07 13:03 UTC, ominitay commented on shaber
> +    if [ -z "$mod_json" ]; then
Same here

2021-09-07 13:06 UTC, ominitay commented on shaber
> +  mod_name=$1
This should be quoted

2021-09-07 13:07 UTC, ominitay commented on shaber
> +  mod_name=$1
Should be quoted

2021-09-07 18:26 UTC, ominitay commented
@mtfurlan I've committed my changes. You may check over them and give me any thoughts you have, then we can get this merged. If you can though, please do try and test out the functionality as much as you can to ensure that the changes behave correctly :)

2021-09-07 19:05 UTC, ominitay approved these changes

2021-09-07 22:16 UTC, ominitay commented
Ah I didn't notice that. Will amend that commit tomorrow. I think I'll hold off merging for a bit just to be sure that I've not introduced any regressions. If you'd like to test it out a bit more, that'd be great, but you don't have to at all :)

2021-10-01 17:46 UTC, ominitay commented
Apologies on taking so long on this, life is fairly busy at the moment. I'll aim to get this merged soon though, and that'll go towards your hacktoberfest if you are participating in that :)

2021-10-02 17:03 UTC, mtfurlan commented
No worries, I get how life happens.
I did find a bug in this though that isn't present on `dev`:
```
1mark@mephala:~/beatSaber/ShellSaber (fix/no-early-fail-if-missing *=)$ ./shaber mod download PlaylistManager                                           
Info: Searching for dependencies for 'PlaylistManager'                                                                                                  
Warn: Mod 'PlaylistManager' is already downloaded. Run 'shaber mod update PlaylistManager' to update it.                                                
mark@mephala:~/beatSaber/ShellSaber (fix/no-early-fail-if-missing *=)$ ./shaber mod update PlaylistManager                                              
Info: Mod 'PlaylistManager' is up-to-date                                                                                                               
1mark@mephala:~/beatSaber/ShellSaber (fix/no-early-fail-if-missing *=)$ ./shaber mod enable PlaylistManager                                             
Error: Dependency 'BeatSaberPlaylistsLib' not downloaded                                                                                                
Error: Failed to get dependency tree for mod 'PlaylistManager'                                                                                          
Error: Failed to enable mod 'PlaylistManager'                                                                                                           
Warn: Errors occured while enabling mods! Please check your logs
```
Let me know if you can't easily replicate it and I'll debug further.

2021-10-02 17:50 UTC, ominitay commented
Yep I can reproduce that too. ShellSaber seemingly isn't downloading the dependencies for the mod. So something bad is clearly happening between creating the dependency list and downloading them. I'll try and debug that later.

2021-10-02 17:58 UTC, ominitay commented
Fixed it, will push an amendment now.

2021-10-03 15:13 UTC, ominitay commented
Made a few final changes, and have finally stopped it from erroring out after running. LGTM

2021-10-03 15:15 UTC, ominitay commented
Nearly forgot to rebase on dev, oops!

2021-10-03 15:28 UTC, merged

2021-10-03 15:34 UTC, ominitay commented
These changes will be included in the next release, which I hope to put out halfway through next week, after I make another couple of changes.

2021-10-03 17:01 UTC, mtfurlan commented
Thank you <3

2021-10-03 17:46 UTC, ominitay commented
Thank you so much for your contributions :)